### ISSUE TITLE
！！建议增加控制每分钟收集能量个数控制的功能！！

### ISSUE THREAD

**Issue by flyinghmx** [TKaxv-7S/Sesame-TK#107]
### 增强类型

功能型增强

### 具体描述

现在使用双击卡，很快会出现“操作异常”的提示，就不能再收能量了，双击卡白用了。我记得之前版本有控制每分钟手机个数的功能，新版本没有了，建议能够恢复。或者其他的防止“操作异常”的控制功能

**Comment by TKaxv-7S** [comment]
后面添加一个双击卡执行间隔的配置就可以了
