### ISSUE TITLE
未来会添加自动收蚂蚁保障金的功能吗

### ISSUE THREAD

**Issue by bocchi810** [TKaxv-7S/Sesame-TK#119]
### 增强类型

功能型增强

### 具体描述

如题，其实我也可以尝试开发，先问一下能不能添加

**Comment by mmmm525** [comment]
已经有了

**Comment by bocchi810** [comment]
> 已经有了

找不到，只找到了攒保障金，没有收

**Comment by Liujishou** [comment]
芝麻粒坚持攒保障金就是啊，这个是为了做芝麻粒里的任务 同时也会收保障金啊

**Comment by bocchi810** [comment]
> 芝麻粒坚持攒保障金就是啊，这个是为了做芝麻粒里的任务 同时也会收保障金啊

不好意思当时没看懂，先关了

**Comment by bocchi810** [comment]
不对啊，为什么我打开了那个功能，怎么没效
