### ISSUE TITLE
额外的能量好像不会自动收取了

### ISSUE THREAD

**Issue by losen21** [TKaxv-7S/Sesame-TK#138]
### 程序版本 / 框架版本 / 模块版本

1.2.7.7

### 系统版本 / Android版本

安卓12

### 详细描述问题发生的具体原因

额外的能量好像不会自动收取了

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by xzcgg** [comment]
3000才会领一次
