### ISSUE TITLE
怎么让小鸡晚上不要睡觉

### ISSUE THREAD

**Issue by wxhbts** [TKaxv-7S/Sesame-TK#140]
### 增强类型

强迫症增强

### 具体描述

然后一次性用完加速卡

**Comment by cry980285208** [comment]
设置里有设置睡觉时间

**Comment by Zhangfanyu1222** [comment]
设置里有个小鸡睡眠时间(范围)

**Comment by buddingworld** [comment]
有时候设置了空或者-1还是会睡觉

**Comment by Zhangfanyu1222** [comment]
> 有时候设置了空或者-1还是会睡觉

前面的数设置大于后面的数就行啦

**Comment by buddingworld** [comment]
> > 有时候设置了空或者-1还是会睡觉
> 
> 前面的数设置大于后面的数就行啦

神奇，我试试，谢谢~
