### ISSUE TITLE
no value for playingresult异常问题，每次执行都报异常

### ISSUE THREAD

**Issue by wushuai2212** [TKaxv-7S/Sesame-TK#142]
### 程序版本 / 框架版本 / 模块版本

1.9.2

### 系统版本 / Android版本

A14  小米hyper系统

### 详细描述问题发生的具体原因

大佬，这个异常是什么意思呢。。一直有

no value for playingresult

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by wushuai2212** [comment]
![ab1608721bb00d825b9116f045bb2e3](https://github.com/TKaxv-7S/Sesame-TK/assets/102722264/aec89b36-7310-4975-86ff-01d272c2988a)

**Comment by TKaxv-7S** [comment]
木兰集市已失效导致，不用管，v1.2.8版本修复了新村其他任务会继续执行，只有木兰集市不会执行，后面会修复或者移除这个功能
