### ISSUE TITLE
功能失效

### ISSUE THREAD

**Issue by luozongkai** [TKaxv-7S/Sesame-TK#152]
### 程序版本 / 框架版本 / 模块版本

1.27

### 系统版本 / Android版本

14

### 详细描述问题发生的具体原因

修改步数功能失效，
小号赠送能量功能失效，
点击导出运行日志软件闪退。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by a824896** [comment]
小号送大号能量，好几个版本都失效了，有时候能送有时候不能送

**Comment by Norman45** [comment]
庄园送麦子失效，会员签到失效，绿色经营收好友金币失效，只管更新不管稳定性了

**Comment by buddingworld** [comment]
原来会员签到是大家都不行 我还以为是我自己原因

**Comment by githubnimabi** [comment]
更新了1.2.9也还是不能签到。。。。
