### ISSUE TITLE
农场种树施肥，如果已经达到兑换条件，建议使用消息通知提醒

### ISSUE THREAD

**Issue by andywu188** [TKaxv-7S/Sesame-TK#160]
### 增强类型

优化型增强

### 具体描述

关于农场种树施肥，如果已经达到兑换条件，建议使用消息通知提醒，仅仅使用日志的话，根本就没注意到，以下是现在的日志:
农场果树似乎可以兑换了！

增加一个手机通知区域提醒

**Comment by baby1128** [comment]
不能自己进去看一眼吗？
