### ISSUE TITLE
小米手机分身应用的使用故障

### ISSUE THREAD

**Issue by huiwin** [TKaxv-7S/Sesame-TK#167]
### 程序版本 / 框架版本 / 模块版本

1.2.8.8、LSPosed 1.9.2

### 系统版本 / Android版本

hyperos-1.0.17.0、Android 14

### 详细描述问题发生的具体原因

首先说明一点、我用的澎湃OS、两个账号一起使用、主账号使用基本没啥问题、但是分身的账号问题还是有的、首先第一次打开之后运行完、就不会自动再次运行了、哪怕是设置了超时重启和异常等待还是不行、必须要从新把后台关掉再次打开才可以、再者就是最近不论是主应用还是双开的副应用发现每天不会自动签到了、上传的日志是双开应用的异常日志

### 提供模块问题 Log 或必要 Log

[error.2024-07-07.log.zip](https://github.com/user-attachments/files/16119694/error.2024-07-07.log.zip)

**Comment by gitnoobbbb** [comment]
澎湃支付宝开分身运行正常，文件系统在各自独立的空间，互不影响
