### ISSUE TITLE
神奇海洋拼图

### ISSUE THREAD

**Issue by DonkeyKong9527** [TKaxv-7S/Sesame-TK#169]
### 增强类型

优化型增强

### 具体描述

现在获取拼图时貌似获取到重复的可以发送更换，所以自动获取拼图时能否增加判断，检测到可更换，就发送更换

**Comment by DonkeyKong9527** [comment]
![IMG_20240709_072131](https://github.com/TKaxv-7S/Sesame-TK/assets/48871252/f4fef938-59fd-4efa-b860-997634cb176a)

**Comment by LazyImmortal** [comment]
会给人发消息的啊……

**Comment by DonkeyKong9527** [comment]
> 会给人发消息的啊……

我看我支付宝信息里没有给人发信息，目前最新版，然后每天重复拼图的数量都在增加，
