### ISSUE TITLE
一直卡在6秒拼手速 打地鼠

### ISSUE THREAD

**Issue by jhjin1998** [TKaxv-7S/Sesame-TK#170]
### 程序版本 / 框架版本 / 模块版本

支付宝10.5.8.8  模块1.2.8.1 

### 系统版本 / Android版本

os: 澎湃1.0.38 ; Android: 14

### 详细描述问题发生的具体原因

从凌晨开始,一直卡在6秒拼手速 打地鼠,知道我早上起来,手动完成打地鼠后,才会收能量.

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

![image](https://github.com/TKaxv-7S/Sesame-TK/assets/46588846/31200eaf-1bbf-49cc-935f-d08a3e4c246e)

**Comment by jhjin1998** [comment]
![image](https://github.com/TKaxv-7S/Sesame-TK/assets/46588846/9034456e-263d-4f87-b36a-022aa5b47b63)
huiyia怀疑是这个地方一直sleep,建议做个超时关闭页面,或者做成 子线程,不影响下面收能量流程

**Comment by TKaxv-7S** [comment]
不是这块代码的问题，方便加讨论区的群提供一份运行日志帮助分析吗

**Comment by jhjin1998** [comment]
> 不是这块代码的问题，方便加讨论区的群提供一份运行日志帮助分析吗

现在只有每天的日志,这个情况是发生在星期六和星期天

**Comment by TKaxv-7S** [comment]
> > 不是这块代码的问题，方便加讨论区的群提供一份运行日志帮助分析吗
> 
> 现在只有每天的日志,这个情况是发生在星期六和星期天

可以先观察一下，下次有异常再导出运行日志，目前收集到的信息太少了，无法定位原因

**Comment by jhjin1998** [comment]
> > > 不是这块代码的问题，方便加讨论区的群提供一份运行日志帮助分析吗
> > 
> > 
> > 现在只有每天的日志,这个情况是发生在星期六和星期天
> 
> 可以先观察一下，下次有异常再导出运行日志，目前收集到的信息太少了，无法定位原因

ok

**Comment by jhjin1998** [comment]
> > > 不是这块代码的问题，方便加讨论区的群提供一份运行日志帮助分析吗
> > 
> > 
> > 现在只有每天的日志,这个情况是发生在星期六和星期天
> 
> 可以先观察一下，下次有异常再导出运行日志，目前收集到的信息太少了，无法定位原因

这个好像是凌晨执行拼手速就会出问题,一直卡在这个页面, 以前也出现过这种情况 比如说8点到23:59 就是正常的

**Comment by TKaxv-7S** [comment]
> > > > 不是这块代码的问题，方便加讨论区的群提供一份运行日志帮助分析吗
> > > 
> > > 
> > > 现在只有每天的日志,这个情况是发生在星期六和星期天
> > 
> > 
> > 可以先观察一下，下次有异常再导出运行日志，目前收集到的信息太少了，无法定位原因
> 
> 这个好像是凌晨执行拼手速就会出问题,一直卡在这个页面, 以前也出现过这种情况 比如说8点到23:59 就是正常的

是的，这个问题断断续续的一直存在，是因为偶尔首页接口不会返回正常首页数据，而是强制返回6秒拼手速的数据，导致收能量的逻辑无法处理而没收取能量，但是这个变化的数据包一直没有抓到，所以一直没有合适的处理方案

**Comment by jhjin1998** [comment]
> > > > > 不是这块代码的问题，方便加讨论区的群提供一份运行日志帮助分析吗
> > > > 
> > > > 
> > > > 现在只有每天的日志,这个情况是发生在星期六和星期天
> > > 
> > > 
> > > 可以先观察一下，下次有异常再导出运行日志，目前收集到的信息太少了，无法定位原因
> > 
> > 
> > 这个好像是凌晨执行拼手速就会出问题,一直卡在这个页面, 以前也出现过这种情况 比如说8点到23:59 就是正常的
> 
> 是的，这个问题断断续续的一直存在，是因为偶尔首页接口不会返回正常首页数据，而是强制返回6秒拼手速的数据，导致收能量的逻辑无法处理而没收取能量，但是这个变化的数据包一直没有抓到，所以一直没有合适的处理方案

行, 那我开起debug吧,到时候出问题,我提供log出来

**Comment by TKaxv-7S** [comment]
> > > > > > 不是这块代码的问题，方便加讨论区的群提供一份运行日志帮助分析吗
> > > > > 
> > > > > 
> > > > > 现在只有每天的日志,这个情况是发生在星期六和星期天
> > > > 
> > > > 
> > > > 可以先观察一下，下次有异常再导出运行日志，目前收集到的信息太少了，无法定位原因
> > > 
> > > 
> > > 这个好像是凌晨执行拼手速就会出问题,一直卡在这个页面, 以前也出现过这种情况 比如说8点到23:59 就是正常的
> > 
> > 
> > 是的，这个问题断断续续的一直存在，是因为偶尔首页接口不会返回正常首页数据，而是强制返回6秒拼手速的数据，导致收能量的逻辑无法处理而没收取能量，但是这个变化的数据包一直没有抓到，所以一直没有合适的处理方案
> 
> 行, 那我开起debug吧,到时候出问题,我提供log出来

好的，非常感谢，不开启抓包也能获取到数据，因为是程序主动请求的，所以只要当时的运行日志没被删除就能找到数据

**Comment by xzcgg** [comment]
森林里的设置6秒拼手速开关不能打开，打开就有可能会出现卡在6秒而无法完成其他任务的问题

**Comment by TKaxv-7S** [comment]
> 森林里的设置6秒拼手速开关不能打开，打开就有可能会出现卡在6秒而无法完成其他任务的问题

最近有出现过吗，只要运行日志还在就可以解决，方便提供开始卡住的运行日志吗

**Comment by jhjin1998** [comment]
> 森林里的设置6秒拼手速开关不能打开，打开就有可能会出现卡在6秒而无法完成其他任务的问题

深林未看到有这个开关,目前使用版本1.2.8.1

**Comment by jhjin1998** [comment]
> > 森林里的设置6秒拼手速开关不能打开，打开就有可能会出现卡在6秒而无法完成其他任务的问题
> 
> 最近有出现过吗，只要运行日志还在就可以解决，方便提供开始卡住

**Comment by Liujishou** [comment]
支付宝 森林界面 右上角三点 设置 6秒 的开关关闭。
