### ISSUE TITLE
切换账号有时会卡好几秒

### ISSUE THREAD

**Issue by buddingworld** [TKaxv-7S/Sesame-TK#171]
### 程序版本 / 框架版本 / 模块版本

v1.2.9-TK

### 系统版本 / Android版本

MIUI14/Android 13

### 详细描述问题发生的具体原因

如题，切换账号有时会卡好几秒，不能稳定复现带概率不算特别低，而且发生后经常出现配置没有重新载入，比如小号也会框框收能量。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by TKaxv-7S** [comment]
方便导出一份运行日志分析吗，不直接发，加群私发给我也可以

**Comment by PinkUicorn** [comment]
大佬群咋加呀，求下

**Comment by TKaxv-7S** [comment]
> 大佬群咋加呀，求下

在讨论区

**Comment by buddingworld** [comment]
[Uploading log.tar.gz…]()


> 方便导出一份运行日志分析吗，不直接发，加群私发给我也可以

刚才点了几次复现了。
![Screenshot_2024-07-09-01-10-30-303_com eg android AlipayGphone](https://github.com/TKaxv-7S/Sesame-TK/assets/109396464/f9b9240f-1530-4660-977d-11def9a7f7e2)
发生时会这样，支付宝黑屏几秒钟。

**Comment by buddingworld** [comment]
> 方便导出一份运行日志分析吗，不直接发，加群私发给我也可以

[Uploading log.tar.gz…]()
[Uploading log.tar.gz…]()

**Comment by buddingworld** [comment]
> 方便导出一份运行日志分析吗，不直接发，加群私发给我也可以

[log.tar.gz](https://github.com/user-attachments/files/16132461/log.tar.gz)
