### ISSUE TITLE
请问大佬可以更新一个读书听书功能和小鸡乐园功能吗？谢谢！

### ISSUE THREAD

**Issue by hgzcrqjdlzrcxt** [TKaxv-7S/Sesame-TK#178]
### 增强类型

功能型增强

### 具体描述

读书听书每日可以获得150g蚂蚁森林能量
蚂蚁庄园小鸡乐园可以获得10个宝箱
这两个太耗费时间了

**Comment by baby1128** [comment]
我也希望增加读书听书功能，因为有能量。。。

**Comment by Liujishou** [comment]
期待你把读书的加密算法搞出来
