### ISSUE TITLE
建议增加光盘行动打卡

### ISSUE THREAD

**Issue by shaoying189** [TKaxv-7S/Sesame-TK#18]
### 增强类型

功能型增强

### 具体描述

光盘行动打卡可以获得107g能量
![Screenshot_2024-06-22-11-51-22-57_3915bacb930634b7e206116f9dc9486f](https://github.com/TKaxv-7S/Sesame-TK/assets/141528141/f08731b1-10d8-4e46-9372-6e7225cbbe1f)

**Comment by 498953584** [comment]
已添加

**Comment by TKaxv-7S** [comment]
> 已添加

谢谢，非常感谢大佬的贡献！
