### ISSUE TITLE
能量检测积极性

### ISSUE THREAD

**Issue by MJRweb** [TKaxv-7S/Sesame-TK#182]
### 增强类型

优化型增强

### 具体描述

能量检测延时太大了的感觉，能优化一下，检测能量的速度嘛，持续检测那种，功耗肯定正比，可以给一个开关，或者优化一下检测速度

**Comment by jhjin1998** [comment]
我只希望检测自己的能量准时一点,每次都被偷,其他好友的随意

**Comment by MJRweb** [comment]
> 我只希望检测自己的能量准时一点,每次都被偷,其他好友的随意

并不是如此，实际情况是好友能量检测更积极，自己的不收，如图
