### ISSUE TITLE
建议增加定时加速器

### ISSUE THREAD

**Issue by 2576005543** [TKaxv-7S/Sesame-TK#189]
### 增强类型

功能型增强

### 具体描述

能收取更多能量做公益

**Comment by xzcgg** [comment]
自动使用加速器，保护罩就别提了，不可能的

**Comment by berebrn** [comment]
> 都是做公益，能量在谁手上不一样？

 大佬，什么时候pr一下海洋 拼图回收再造功能谢谢！

**Comment by LazyImmortal** [comment]
> > 都是做公益，能量在谁手上不一样？
> 
> 大佬，什么时候pr一下海洋 拼图回收再造功能谢谢！

这个需要万能拼图时再手动去换一下不就好了吗？我万能拼图都完全用不上……

**Comment by berebrn** [comment]
> > > 都是做公益，能量在谁手上不一样？
> > 
> > 
> > 大佬，什么时候pr一下海洋 拼图回收再造功能谢谢！
> 
> 这个需要万能拼图时再手动去换一下不就好了吗？我万能拼图都完全用不上……

好的 ，谢谢
