### ISSUE TITLE
建议增加日常记录获取芝麻粒

### ISSUE THREAD

**Issue by 12tig** [TKaxv-7S/Sesame-TK#192]
增强类型

功能型增强

### 具体描述

建议增加防骗打卡和每日领取会员积分 这两个也可以积攒芝麻粒
![Uploading Screenshot_2024-07-12-09-14-11-634_com.eg.android.AlipayGphone.jpg…]()

**Comment by baby1128** [comment]
防骗打卡如果选错答案，当日的任务无法完成的。
但似乎重新进行防骗评估，也能完成任务？（这一个需要测试验证）
