### ISSUE TITLE
希望大佬增加一个每日自动给被收能量最多的前几位返水

### ISSUE THREAD

**Issue by 12tig** [TKaxv-7S/Sesame-TK#193]
### 增强类型

功能型增强

### 具体描述

每天晚上八点之前或者某个时间给被收取最多的前三位没人返水

**Comment by LazyImmortal** [comment]
既然舍不得返水，那就不要返水。
![tkaxv7s.xposed.sesame](https://github.com/user-attachments/assets/7f00c2c1-6bb1-4096-bc84-9f3e082291d5)
