### ISSUE TITLE
支付宝会员不会自动签到

### ISSUE THREAD

**Issue by githubnimabi** [TKaxv-7S/Sesame-TK#194]
### 程序版本 / 框架版本 / 模块版本

面具27.0，LSP1.9.2，TK版本1.2.9C-TK，支付宝10.5.10.8100

### 系统版本 / Android版本

MIUI14，android13

### 详细描述问题发生的具体原因

从1.2.7版本开始，支付宝会员不能自动签到，希望大佬有时间的话看一下，感谢

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

抱歉，不知道从哪里提取runtime日志

**Comment by Sixteennights1006** [comment]
我没有遇到过，正常签到的啊

**Comment by githubnimabi** [comment]
> 我没有遇到过，正常签到的啊

我看酷安里也有好多人反应说不能签到，，也不是一直不能，有时候能签到，有时候不能，大多数时候不能签到，要杀掉支付宝之后再打开，不能签到的话，等一分钟左右，就在杀掉，再打开，重复几次有时候就能签到

**Comment by buddingworld** [comment]
版本太老了吧 更新试试 我之前不行现在行

**Comment by githubnimabi** [comment]
> 版本太老了吧 更新试试 我之前不行现在行

支付宝版本太老了么？还是插件的版本？

**Comment by buddingworld** [comment]
> > 版本太老了吧 更新试试 我之前不行现在行
> 
> 支付宝版本太老了么？还是插件的版本？

插件呗 反正我的现在一堆号都没问题

**Comment by githubnimabi** [comment]
> > > 版本太老了吧 更新试试 我之前不行现在行
> > 
> > 
> > 支付宝版本太老了么？还是插件的版本？
> 
> 插件呗 反正我的现在一堆号都没问题

好的，多谢，我再试试，发现不能自动签到之后，我也更新了三四次插件，结果都一样

**Comment by ritaferni** [comment]
你不要看会员页面上显示当日签到那个7积分还在，就以为没有签到，实际上早签到了。你要点进积分明细页面去看，就知道早就签到了

**Comment by githubnimabi** [comment]
> 你不要看会员页面上显示当日签到那个7积分还在，就以为没有签到，实际上早签到了。你要点进积分明细页面去看，就知道早就签到了

我就是点进去看的，点进去之后，会自动签到，然后看签到时间，就是刚刚的时间，，，，我知道个人中心那个页面，显示的7个积分未领取会不太准确
