### ISSUE TITLE
网商银行福利金

### ISSUE THREAD

**Issue by Nichovlasy** [TKaxv-7S/Sesame-TK#199]
### 增强类型

功能型增强

### 具体描述

之前在1.2.5.8-TK版本更新了网商银行福利金的功能，但是在1.2.6.7-TK这个功能又没有了，到后续版本都没有，希望大佬可以恢复这个功能。
![Screenshot_2024-07-13-08-55-40-027_tkaxv7s xposed sesame](https://github.com/user-attachments/assets/571d034b-240d-428a-951c-6927f23494bd)
![Screenshot_2024-07-13-08-56-06-397_tkaxv7s xposed sesame](https://github.com/user-attachments/assets/4c599298-7c04-4619-bafa-b4a8566c49c2)
![IMG_20240713_090000](https://github.com/user-attachments/assets/852af494-cd3e-4411-891d-799fcf664c97)
![Screenshot_2024-07-13-09-00-27-056_tkaxv7s xposed sesame](https://github.com/user-attachments/assets/632e89d5-3fb2-4c5e-8f0b-cff4f9812763)
![Screenshot_2024-07-13-09-00-32-482_tkaxv7s xposed sesame](https://github.com/user-attachments/assets/167319b3-6c26-4483-9fd6-33477b1484a4)

**Comment by Liujishou** [comment]
不会加

**Comment by Nichovlasy** [comment]
@498953584 大佬，这个网商银行福利金是你1.2.5.8的时候贡献的，但是后续版本没这个功能了，请问可以恢复这个功能吗

**Comment by Nichovlasy** [comment]
> 不会加

请问大佬是不知道具体功能如何实现还是这个功能本身不方便加
