### ISSUE TITLE
1.3.0送麦子好友列表无法勾选

### ISSUE THREAD

**Issue by Nichovlasy** [TKaxv-7S/Sesame-TK#205]
### 程序版本 / 框架版本 / 模块版本

1.3.0-T1-TK

### 系统版本 / Android版本

hyperOS1.0.18 Android14

### 详细描述问题发生的具体原因

庄园送好友吉祥麦列表无法勾选
![Screenshot_2024-07-13-23-19-46-984_tkaxv7s xposed sesame-edit](https://github.com/user-attachments/assets/f80f2b95-ed91-4cae-926f-650ef8cbfb19)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by xzcgg** [comment]
不需要√选，后面输入次数就行

**Comment by Nichovlasy** [comment]
> 不需要√选，后面输入次数就行

好的好的
