### ISSUE TITLE
车辆停驶 每周一次 819g

### ISSUE THREAD

**Issue by xiaolanchong123** [TKaxv-7S/Sesame-TK#217]
### 增强类型

功能型增强

### 具体描述

车辆停驶 每周一次 819g
大佬有没有兴趣加一下

**Comment by dsjun007** [comment]
这个要拍油表，三天内审核，感觉像真的是人工审核

**Comment by dsjun007** [comment]
您好，来信已收到！

**Comment by 0only** [comment]
确实审核也轻松过,我都用照片快一年了 ,时不时更换照片
