### ISSUE TITLE
强烈建议先把最基础的偷能量功能优化好

### ISSUE THREAD

**Issue by mmmm525** [TKaxv-7S/Sesame-TK#219]
### 增强类型

功能型增强

### 具体描述

一路用上来,到现在的1.2.28,摸能量一直不行,所以一直用两个模块,三个模块,各项功能互补,不管是原版的芝麻粒,还是水晶,曜,还是VoltX,举个例子,其他软件能摸1000,现在芝麻粒TK只能摸700,每版更新我都试过,用一天,就现在的1.2.28,我用原版的能摸2200,用1.2.28,今天只有1100,到晚上最多1500,芝麻粒一路升级,功能是越来越多,然后牵扯到利益的功能,有去阉割,框架越来越大,但是最基础的蚂蚁森林,一直很拉胯,摸能量既没有利益,又是最要功能,为什么不把这项功能优化到最好呢...
当然这只是建议,各大作者都是用爱发电,非常感谢
![QQ截图20240716092359](https://github.com/user-attachments/assets/817f52f0-6b15-43ff-b786-97002c197bfa)
![QQ截图20240716092415](https://github.com/user-attachments/assets/b89c885c-fd98-478e-a542-1495a730d903)
![QQ截图20240716092426](https://github.com/user-attachments/assets/db4ae08e-8f97-40e5-8b44-a2f7836a5174)

**Comment by PinkUicorn** [comment]
有没有一种可能水每天也并不固定呢，会是正常波动呢。偷能量的逻辑有没有可能现在已经是不错的设计了。目前偷能量代码也许并不是想象中稍作添砖加瓦，就能更好，更快，更精准了。而是可能要重新推倒，重新构思那类了。费时间精力不说，成品也不一定有你想象的那种效果。
你类似的情况我也有过，后来查漏发现是双击相关的问题，找到了作者反馈，也马上解决了。你可以先自查找到问题，如果不是bug产生的那其实就没必要要求什么了。大多数人应该还是用着不错所以才没问题，如果是大面积bug或者使用体验不好作者也会注意到。
TK大佬把开发门槛也降低了，能看到很多加进来的是许多其他热心网友贡献的代码做的功能，也许你也可以花些功夫将你很关心的内容做一些添砖加瓦。
以上有你觉得没道理的还请谅解不跟我一般见识或者骂我两句撒气。
