### ISSUE TITLE
1.2.5.8合并过的福利金功能自1.2.6以后没有了

### ISSUE THREAD

**Issue by Nichovlasy** [TKaxv-7S/Sesame-TK#224]
### 增强类型

功能型增强

### 具体描述

https://github.com/TKaxv-7S/Sesame-TK/pull/23#issue-2368108913

福利金功能在1.2.5.8合并生效，但是在之后的版本都没有这个功能

**Comment by Zhangfanyu1222** [comment]
合并后就砍掉了 看readme
![image](https://github.com/user-attachments/assets/446514d2-f435-444e-ba26-99e8f11ad27a)

**Comment by Nichovlasy** [comment]
> 合并后就砍掉了 看readme ![图像](https://private-user-images.githubusercontent.com/65014915/349310648-446514d2-f435-444e-ba26-99e8f11ad27a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExODY2NDQsIm5iZiI6MTcyMTE4NjM0NCwicGF0aCI6Ii82NTAxNDkxNS8zNDkzMTA2NDgtNDQ2NTE0ZDItZjQzNS00NDRlLWJhMjYtOTllOGYxMWFkMjdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDAzMTkwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MmQzMTA5OWExZjk0ZWVjMjQ5NDczOGZkMDhjODQ1ZGEwY2M3ZTljNzE1YWE4NmVhZDhmZjkyMTgwYWJkZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Az0kMwxBs086hOsFEJTy-41KdI-ZWh6-wNGsA3QJazY)

好的，谢谢
