### ISSUE TITLE
蹲点收取能量时间误差很大,造成能量收取失败

### ISSUE THREAD

**Issue by jhjin1998** [TKaxv-7S/Sesame-TK#225]
### 程序版本 / 框架版本 / 模块版本

支付宝: 10.5.66      芝麻粒: 1.2.28

### 系统版本 / Android版本

os: 澎湃1.0.38 ; Android: 14

### 详细描述问题发生的具体原因

蹲点设置的时间误差很大,比如说 想想算什么是在07:09:00 能量收取的296g,但是程序吧时间定在了07:09:26,其他好友的收取时间亦然.详细查看如下日志:
![89e0645881673309280a5f6a5c1f44f](https://github.com/user-attachments/assets/e064fc78-9e1b-499d-907e-a671adad6568)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

![89e0645881673309280a5f6a5c1f44f](https://github.com/user-attachments/assets/6e894019-93bc-4737-9eaa-ced246fa04cf)
收取失败日志:
![355d225d0fa46af1cf5367b1ae0b456](https://github.com/user-attachments/assets/a328640e-39f7-4977-88b7-929416f88982)

**Comment by jhjin1998** [comment]
造成很多能量收不上来,定时任务给了,说明逻辑没有问题, 但是都是收取失败-重试, 希望定时的** 时间**上面可以做一下优化,可以更精准一些

**Comment by jhjin1998** [comment]
支付宝版本写错了,是**10.5.8.8**

**Comment by mmmm525** [comment]
我也反馈过收能量有问题,结果被人长篇大论说了一顿,算咯,本来就是用爱发电  不强求  还是用几个模块,分功能使用互补一下吧

**Comment by mmmm525** [comment]
而且不开启收能量,用其他模块收能量的话,功能里面的隐身卡还无法使用,没反应

**Comment by jhjin1998** [comment]
> 我也反馈过收能量有问题,结果被人长篇大论说了一顿,算咯,本来就是用爱发电 不强求 还是用几个模块,分功能使用互补一下吧

其实没事啊,我们也是为了这个开源项目更好才提出意见,又不是为了撒. 他提出他的想法,说明他也思考了,没得问题,只是角度不同而已.  我们只需要提自己的就行,没必要辩论.  改不改是一回事,毕竟是开源的,不用奢求太多,  我对这个也不是很执着,只是觉得代码写得不错,至少结构这方面很不错. 我感觉有必要去要求更好的.

**Comment by PinkUicorn** [comment]
> 我也反馈过收能量有问题,结果被人长篇大论说了一顿,算咯,本来就是用爱发电 不强求 还是用几个模块,分功能使用互补一下吧

老哥我觉得反馈问题不能带命令或者职责的口吻。我为我说的向你道个歉，确实也带了点主观情绪可能让你觉得有点说教。
其实收能量效率问题我也有注意到的，就像之前反馈了双击bug。只是觉得目前确实整体还不错，偶尔少偷了点能量其实也别太在意。我列表挂b很多，其实一个插件再好也抢不过来，开多个互补是好很多的，是个不错的解决方法。这两天我的能量偷取也少的，（而且发现一个问题，设置的尝试次数过了以后，便不再继续收取了，导致错失了）今天我试着TK版调整收取提前时间和次数，看是否能改善。

**Comment by LazyImmortal** [comment]
> 而且不开启收能量,用其他模块收能量的话,功能里面的隐身卡还无法使用,没反应

永动机就是在收能量前判断是否需要使用的道具的
