### ISSUE TITLE
神奇物种交换卡片

### ISSUE THREAD

**Issue by charleyyy** [TKaxv-7S/Sesame-TK#238]
### 增强类型

功能型增强

### 具体描述

建议增加神奇物种帮好友抽卡后交换选项。
帮好友抽卡后有时候抽到图鉴中没有的卡片，可以用已有（超过两张）的卡片交换，要不会出现抽到没有的卡片也浪费的情况。

**Comment by LazyImmortal** [comment]
伪需求！只要每天抽卡，抽到完整特辑的概率是百分之百！而且交换卡片还要给好友发消息，要加你可以自己PR。
