### ISSUE TITLE
平繁检测超时

### ISSUE THREAD

**Issue by MJRweb** [TKaxv-7S/Sesame-TK#240]
### 程序版本 / 框架版本 / 模块版本

程序版本10.6.13.8000     框架版本 lsp1.9.2     模块版本v1.3.0-T 9-TK    

### 系统版本 / Android版本

澎湃OS / Android14

### 详细描述问题发生的具体原因

设置的检测超时异常等待时间是10分钟，支付宝自启动开了的，后台保活也开了

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

00:48:41.341 执行失败：检查超时
00:51:41.344 应用版本：10.6.13.8000
00:51:41.344 模块版本：v1.3.0-T9-TK
00:51:41.344 开始执行
00:51:51.371 执行失败：检查超时
00:54:51.376 应用版本：10.6.13.8000
00:54:51.376 模块版本：v1.3.0-T9-TK
00:54:51.376 开始执行
00:55:01.408 执行失败：检查超时
00:58:01.413 应用版本：10.6.13.8000
00:58:01.413 模块版本：v1.3.0-T9-TK
00:58:01.413 开始执行
00:58:11.440 执行失败：检查超时
01:01:11.455 应用版本：10.6.13.8000
01:01:11.455 模块版本：v1.3.0-T9-TK
01:01:11.455 开始执行
01:01:21.485 执行失败：检查超时
01:04:21.499 应用版本：10.6.13.8000
01:04:21.499 模块版本：v1.3.0-T9-TK
01:04:21.499 开始执行
01:04:31.532 执行失败：检查超时
01:04:39.747 模块版本：v1.3.0-T9-TK
01:04:39.747 开始加载
01:04:39.749 加载配置: 2088042928232848
01:04:40.041 取消定时唤醒:0|000000
01:04:40.045 设置定时唤醒:0|000000
01:04:40.048 设置定时唤醒:1|2350
01:04:40.103 加载完成
01:04:40.104 应用版本：10.6.13.8000
01:04:40.104 模块版本：v1.3.0-T9-TK
01:04:40.104 开始执行
01:04:50.119 执行失败：检查中断
01:04:50.160 应用版本：10.6.13.8000
01:04:50.160 模块版本：v1.3.0-T9-TK
01:04:50.160 开始执行
01:05:00.179 执行失败：检查超时
01:05:05.182 应用版本：10.6.13.8000
01:05:05.182 模块版本：v1.3.0-T9-TK
01:05:05.182 开始执行
01:05:15.202 执行失败：检查超时
01:05:25.207 应用版本：10.6.13.8000
01:05:25.207 模块版本：v1.3.0-T9-TK
01:05:25.207 开始执行
01:05:35.246 执行失败：检查超时
01:05:50.253 应用版本：10.6.13.8000
01:05:50.254 模块版本：v1.3.0-T9-TK
01:05:50.254 开始执行
01:06:00.288 执行失败：检查超时
01:06:20.291 应用版本：10.6.13.8000
01:06:20.291 模块版本：v1.3.0-T9-TK
01:06:20.291 开始执行
01:06:30.320 执行失败：检查超时
01:09:30.328 应用版本：10.6.13.8000
01:09:30.328 模块版本：v1.3.0-T9-TK
01:09:30.328 开始执行
01:09:40.352 执行失败：检查超时
01:12:40.362 应用版本：10.6.13.8000
01:12:40.362 模块版本：v1.3.0-T9-TK
01:12:40.362 开始执行
01:12:50.387 执行失败：检查超时
01:15:50.409 应用版本：10.6.13.8000
01:15:50.409 模块版本：v1.3.0-T9-TK
01:15:50.409 开始执行
01:16:00.441 执行失败：检查超时
01:19:00.454 应用版本：10.6.13.8000
01:19:00.454 模块版本：v1.3.0-T9-TK
01:19:00.454 开始执行
01:19:10.475 执行失败：检查超时
01:22:10.485 应用版本：10.6.13.8000
01:22:10.485 模块版本：v1.3.0-T9-TK
01:22:10.485 开始执行
01:22:20.512 执行失败：检查超时
01:25:20.550 应用版本：10.6.13.8000

</code></pre></details>

**Comment by MJRweb** [comment]
![Uploading Screenshot_2024-07-19-06-46-45-535_tkaxv7s.xposed.sesame.jpg…]()

**Comment by MJRweb** [comment]
![Screenshot_2024-07-19-06-46-45-535_tkaxv7s xposed sesame](https://github.com/user-attachments/assets/20d1cb3e-1a11-4e4b-87da-cae3317dff4c)
![Screenshot_2024-07-19-06-33-43-526_tkaxv7s xposed sesame](https://github.com/user-attachments/assets/75ecda51-2d0b-46f5-8ade-b7ce3f3ad7e5)

**Comment by Liujishou** [comment]
这是你支付给限制网络了，自己检查下系统限制问题

**Comment by xzcgg** [comment]
锁后台，自启动，无限制，关睡眠模式
