### ISSUE TITLE
运动项目里训练好友会修改好友备注名

### ISSUE THREAD

**Issue by Vstory** [TKaxv-7S/Sesame-TK#262]
### 程序版本 / 框架版本 / 模块版本

LSPosed 1.9.2(7058) 芝麻粒1.2.100

### 系统版本 / Android版本

13

### 详细描述问题发生的具体原因

开启运动项目里的训练好友，好友的备注名会被加上 "提醒-" 

### 提供模块问题 Log 或必要 Log

![Screenshot_2024-07-23-11-05-55-903_tkaxv7s xposed sesame](https://github.com/user-attachments/assets/bda65c27-4edb-4af4-a42c-9b447b4ffde4)

**Comment by Vstory** [comment]
实际中，好友备注名会被加上该字段。

**Comment by LazyImmortal** [comment]
其他软件改的

**Comment by Vstory** [comment]
https://github.com/TKaxv-7S/Sesame-TK/pull/16/commits/b93e798d53bf78df7ee8368284a6fcb29e24be5f

之前改名了，我修改回去了，目前查看好友备注，暂未修改，看看明天会不会改。

**Comment by LazyImmortal** [comment]
> [b93e798](https://github.com/TKaxv-7S/Sesame-TK/commit/b93e798d53bf78df7ee8368284a6fcb29e24be5f)
> 
> 之前改名了，我修改回去了，目前查看好友备注，暂未修改，看看明天会不会改。

提交的代码里没有修改备注，应该是其他插件修改的。如果你没有安装其他插件，那可能是你安装的内置版支付宝内置了别的会修改备注的插件（比如XQ_Crystal）。

**Comment by Vstory** [comment]
> > [b93e798](https://github.com/TKaxv-7S/Sesame-TK/commit/b93e798d53bf78df7ee8368284a6fcb29e24be5f)
> > 之前改名了，我修改回去了，目前查看好友备注，暂未修改，看看明天会不会改。
> 
> 提交的代码里没有修改备注，应该是其他插件修改的。如果你没有安装其他插件，那可能是你安装的内置版支付宝内置了别的会修改备注的插件（比如XQ_Crystal）。

我是真的没有其他插件😥

**Comment by amulin202** [comment]
> > > [b93e798](https://github.com/TKaxv-7S/Sesame-TK/commit/b93e798d53bf78df7ee8368284a6fcb29e24be5f)
> > > 之前改名了，我修改回去了，目前查看好友备注，暂未修改，看看明天会不会改。
> > 
> > 提交的代码里没有修改备注，应该是其他插件修改的。如果你没有安装其他插件，那可能是你安装的内置版支付宝内置了别的会修改备注的插件（比如XQ_Crystal）。
> 
> 我是真的没有其他插件😥

有没有可能之前用过其他的，里面是有些单删和提醒的备注。

**Comment by Vstory** [comment]
> > > > [b93e798 货号 B93E798](https://github.com/TKaxv-7S/Sesame-TK/commit/b93e798d53bf78df7ee8368284a6fcb29e24be5f)
> > > > 之前改名了，我修改回去了，目前查看好友备注，暂未修改，看看明天会不会改。
> > > 
> > > 
> > > 提交的代码里没有修改备注，应该是其他插件修改的。如果你没有安装其他插件，那可能是你安装的内置版支付宝内置了别的会修改备注的插件（比如XQ_Crystal）。
> > 
> > 
> > 我是真的没有其他插件😥
> 
> 有没有可能之前用过其他的，里面是有些单删和提醒的备注。

也有可能吧 谢谢
