### ISSUE TITLE
游戏中心建议增加随机间隔完成一个任务

### ISSUE THREAD

**Issue by donglex** [TKaxv-7S/Sesame-TK#29]
### 增强类型

优化型增强

### 具体描述

游戏中心的所有任务在一秒内都完成了，这是否会引起工作人员的疑问？万一把所有的豆都给清零了就不太好了。建议随机间隔完成一个任务？

**Comment by 498953584** [comment]
安排，每个任务加上等待配置的间隔时间。

**Comment by donglex** [comment]
> 安排，每个任务加上等待配置的间隔时间。

是否考虑会员任务也加上随机间隔呢？有些任务是浏览15s后才能完成。
