### ISSUE TITLE
建议增加这些功能，极大提升使用体验，感谢大佬

### ISSUE THREAD

**Issue by xzcgg** [TKaxv-7S/Sesame-TK#3]
### 增强类型

功能型增强

### 具体描述

兑换不限时能量双击卡 、不限时能量保护罩
自动完成光盘行动
账号破五
膜拜大佬

**Comment by Bs-2195** [comment]
光盘行动是需要即时拍照的，可能无法实现

**Comment by Zhangfanyu1222** [comment]
> 光盘行动是需要即时拍照的，可能无法实现

你在另一台设备保存两张图片，每天打开拍照一下就行

**Comment by xzcgg** [comment]
> 光盘行动是需要即时拍照的，可能无法实现

一直有在用其他模块的光盘行动

**Comment by Andyqiu-rm** [comment]
> > 光盘行动是需要即时拍照的，可能无法实现
> 
> 一直有在用其他模块的光盘行动

已经加入这个功能，正常使用
