### ISSUE TITLE
神奇海洋：每日任务帮好友收垃圾后无法领取奖励

### ISSUE THREAD

**Issue by paolo8341** [TKaxv-7S/Sesame-TK#30]
### 程序版本 / 框架版本 / 模块版本

10.6.8/LSPosed 1.9.2/1.2.5.6

### 系统版本 / Android版本

MIUI Android13

### 详细描述问题发生的具体原因

收取好友垃圾后，任务还在，不能领取奖励

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by berebrn** [comment]
![5f6a940afe5d7aac3e851b03c563a5c](https://github.com/TKaxv-7S/Sesame-TK/assets/140738041/851758fe-487f-415a-a892-cab98486d31b)
更新最新版试试
