### ISSUE TITLE
增加屏蔽更新支付宝客户端提示

### ISSUE THREAD

**Issue by forkWo** [TKaxv-7S/Sesame-TK#32]
### 增强类型

强迫症增强

### 具体描述

用低版本支付宝会时不时提示更新

**Comment by yi-boide** [comment]
更新到最新版不就好了，最新版也支持的，不更新有些支付宝的功能还使用不了

**Comment by Zhangfanyu1222** [comment]
> 更新到最新版不就好了，最新版也支持的，不更新有些支付宝的功能还使用不了

在用低版本破5的小伙伴就不会去升级支付宝咯
