### ISSUE TITLE
神奇海洋增加指定好友不清理垃圾的功能

### ISSUE THREAD

**Issue by paolo8341** [TKaxv-7S/Sesame-TK#36]
### 增强类型

功能型增强

### 具体描述

弄一个清理垃圾的名单列表，打钩的不清理

**Comment by Zhangfanyu1222** [comment]
不清理垃圾名单，是直接用的森林中不收能量名单
![image](https://github.com/TKaxv-7S/Sesame-TK/assets/65014915/0f7ec76a-bb8f-4bca-ba62-2f501a8b186d)

**Comment by paolo8341** [comment]
好的，我试试。

**Comment by Zhangfanyu1222** [comment]
> 好的，我试试。

嗯呐~代码里是酱紫哒😜
