### ISSUE TITLE
绿色经营增加收取好友金币功能

### ISSUE THREAD

**Issue by Norman45** [TKaxv-7S/Sesame-TK#39]
### 增强类型

功能型增强

### 具体描述

大佬既然已经开始做绿色经营了，挑战一下开发收取好友金币功能试试，目前官方就只能收前10位好友金币，希望可以收取全部好友金币。金币换福利金，福利金在用网商银行付款当钱用。之前芝麻粒第一位开发遗留了一个问题，只做了任务，赚的金币要手工收取，希望修复。

**Comment by 498953584** [comment]
本来想加个自动兑换功能的，但是没抓到包；
收好友金币可以看看。

**Comment by Norman45** [comment]
感谢大佬！因为兑换每月次数限制，最好就是金币收集到一万按最高一万金币兑换最划得来，不然浪费次数，所以自动兑换没弄出来也没事，目前手工兑换最好。现在就是金币太难收取，如果收取好友功能弄出来，自动兑换最大一万金币也可行。
  收取好友金币就是逻辑可能不是很简单，要类似收取森林能量那样的逻辑。加油大佬！
![Screenshot_20240624_230551_com eg android AlipayGphone](https://github.com/TKaxv-7S/Sesame-TK/assets/31527054/dad10587-92e5-4ced-ab4c-3cac1deeed7e)

**Comment by 498953584** [comment]
这玩意还分等级的呀，我的一级一天就500。。。刚刚准备看收好友金币的，看着看着又看到做拍摄任务的去了（因为光盘行动也有拍摄想着可能差不多）

**Comment by Norman45** [comment]
对的，分等级的，最高五级，等级越高每周领的金币越多(头像查看里面)，相同金币兑换福利金比例越高，还有这等级一会四级一会五级感觉都有bug。想起来了，那个任务里面一个月会出现一两回垃圾桶和环保袋的拍摄任务，有助于提升等级，我这里还有图片可以参考。
![2013032917534504_old](https://github.com/TKaxv-7S/Sesame-TK/assets/31527054/4097ccc3-14ec-4a0b-92ad-c388f8cce561)

![Screenshot_20240624_234807_com eg android AlipayGphone](https://github.com/TKaxv-7S/Sesame-TK/assets/31527054/57bee6b3-187d-438d-80c5-8e789f559a52)
![IMG_20240210_002447](https://github.com/TKaxv-7S/Sesame-TK/assets/31527054/99bd4c68-fcbf-4d4d-a62d-c308f1846068)
