### ISSUE TITLE
一些优化使用体验建议

### ISSUE THREAD

**Issue by Norman45** [TKaxv-7S/Sesame-TK#40]
### 增强类型

功能型增强

### 具体描述

1.神奇物种可以加一个设置是否使用道具，因为希望下个图鉴第一天可以有道具用
2.建议芭芭农场设置个开关控制是否雇佣被人小鸡除草，小号每次会把其他小号雇佣了，也容易被别人骂
3.建议海洋提醒好友收垃圾，只提醒那些1级不玩的，或者加个指定提醒好友列表

**Comment by Zhangfanyu1222** [comment]
捉鸡其实有个白名单的，用的是庄园的不通知赶鸡列表😂
![image](https://github.com/TKaxv-7S/Sesame-TK/assets/65014915/685f92b1-0ce2-4516-ae83-0b482b6e1f5c)

**Comment by Norman45** [comment]
海洋和神奇物种也可以研究研究
