### ISSUE TITLE
收能量异常断档，无任何响应和错误日志

### ISSUE THREAD

**Issue by schalkiii** [TKaxv-7S/Sesame-TK#51]
### 程序版本 / 框架版本 / 模块版本

1.2.5.8

### 系统版本 / Android版本

Android 12

### 详细描述问题发生的具体原因

早上七点能量高峰，图中日志7点05开始断档不收能量到8点27才开始恢复收取。也没有报收取能量异常

![e53878c623d59f0abda7f67c7808ff0](https://github.com/TKaxv-7S/Sesame-TK/assets/30932387/ed109869-1be0-471d-bcdf-a32c876af28e)

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by s36376149** [comment]
检查网络是否连接，后台是否加锁，系统是否有锁屏限制进程

**Comment by s36376149** [comment]
大家想要的东西在这里。下载后只要把11去掉就可以下载了。但不保证下载的速度！http://pan.baidu.com/s/1i4IK8BV这里还有好东西。http://pan.baidu.com/s/1eRKS9Eihttp://pan.baidu.com/s/1eS4TKmmhttp://pan.baidu.com/s/1kUA8Zcz
