### ISSUE TITLE
赠送森林道具至主账号  导致主账号自我循环赠送/领取问题

### ISSUE THREAD

**Issue by ooil929** [TKaxv-7S/Sesame-TK#52]
### 程序版本 / 框架版本 / 模块版本

v1.2.6-test4-TK

### 系统版本 / Android版本

Android 14

### 详细描述问题发生的具体原因

当赠送森林道具并选定主账号为接收方后，若操作流程中子账号完成赠送并切换至主账号接收道具，会导致主账号错误地启动自我赠送/自我接收流程，陷入无限循环状态。建议增加当前登录账号与道具接收方账号一致时 不触发赠送道具。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by acooler15** [comment]
多个账号共用一个配置文件？

**Comment by ritaferni** [comment]
最新版1.2.6.2，也发生了同样情形，同安卓14。

**Comment by zyk1994** [comment]
我也遇到了这个问题，自己送自己道具然后日志疯狂刷屏😭

**Comment by DonkeyKong9527** [comment]
1.2.7同样遇到相同问题，自我赠送自我接收，搞了几百个

**Comment by a824896** [comment]
把主账号赠送道具取消自己就行了

**Comment by DonkeyKong9527** [comment]
主账号并没有启用赠送，也没有启用兑换

**Comment by zyk1994** [comment]
> 把主账号赠送道具取消自己就行了

大号没勾选，只有小号勾选了大号，然后大号就疯狂自己送自己道具

**Comment by TKaxv-7S** [comment]
v1.2.7.1应该已修复

**Comment by ooil929** [comment]
done
