### ISSUE TITLE
森林模块提前收取时间无法修改

### ISSUE THREAD

**Issue by schalkiii** [TKaxv-7S/Sesame-TK#6]
### 程序版本 / 框架版本 / 模块版本

1.2.5

### 系统版本 / Android版本

Android 11

### 详细描述问题发生的具体原因

森林模块提前收取时间无法修改，修改无法生效，被固定在250ms。即便进入json文件手动修改advanceTime字段，打开app也会显示250ms并修改回250ms

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by schalkiii** [comment]
另外能否请教一下收取间隔和重试间隔的差别。收取间隔是成功收取之间的间隔是吗，如果收取A成功同时B也在重试收取哪个优先级更高呢

**Comment by TKaxv-7S** [comment]
提前时间不能小于250ms，多了会出现异常，所以设大了没有意义，收取间隔是成功的间隔，A和B同时执行看哪个线程先获取到对象锁谁就先执行，没有限制先后顺序
