### ISSUE TITLE
兑换双击卡异常

### ISSUE THREAD

**Issue by miaowyg** [TKaxv-7S/Sesame-TK#60]
### 程序版本 / 框架版本 / 模块版本

10.6.8  ，1.9.2  ，1.2.6 test5

### 系统版本 / Android版本

澎湃os，安卓13

### 详细描述问题发生的具体原因

如题，第一次使用，设置都只兑换一次，发现退出重进后，日志记录又兑换一次，是否正常？

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

[Uploading runtime.2024-06-27.log…]()

**Comment by s36376149** [comment]
查看一下自己设置的兑换多少张
