### ISSUE TITLE
每天过0点后，森林记录和庄园记录，显示的还是昨天的，打开是空白的，要重新关闭芝麻粒后打开，才能正常

### ISSUE THREAD

**Issue by success-crypto** [TKaxv-7S/Sesame-TK#63]
### 程序版本 / 框架版本 / 模块版本

10.6.8.8000 / 1.9.2 / v1.2.6-test6-TK

### 系统版本 / Android版本

12

### 详细描述问题发生的具体原因

每天过0点后，森林记录和庄园记录，显示的还是昨天的，打开是空白的，要重新关闭芝麻粒后打开，才能正常

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by xzcgg** [comment]
目前任务是在00:05才开始做

**Comment by amulin202** [comment]
森林记录和庄园记录都是昨天的，打开又是空白的？那是指哪里看的是昨天的？

**Comment by success-crypto** [comment]
> 森林记录和庄园记录都是昨天的，打开又是空白的？那是指哪里看的是昨天的？

例如在2024年6月27日记录显示全部是正常的，但是到了2024年6月28日00:00后，再打开查看森林和庄园的记录左上角的日志文件依旧会显示2024年6月27日的log文件名称，并且日志界面为空白，需要将芝麻粒强制关闭后再重新打开才能正常显示2024年6月28日的log（上述所有描述只针对森林记录和庄园记录两个单独的日志入口，查看全部日志显示是正常的）

**Comment by success-crypto** [comment]
> 目前任务是在00:05才开始做

过了0点后 一定需要强制关闭再重新打开才能正常显示，也就是说即使到了00:05后，如果不强制关闭再重新打开依旧不会正常显示日志（只是显示不正常哈，任务还是在正常跑的）

**Comment by TKaxv-7S** [comment]
> > 目前任务是在00:05才开始做
> 
> 过了0点后 一定需要强制关闭再重新打开才能正常显示，也就是说即使到了00:05后，如果不强制关闭再重新打开依旧不会正常显示日志（只是显示不正常哈，任务还是在正常跑的）

了解，这个问题一直有，之前没处理，后面会修复一下了
