### ISSUE TITLE
增加支付宝保活机制

### ISSUE THREAD

**Issue by success-crypto** [TKaxv-7S/Sesame-TK#64]
### 增强类型

功能型增强

### 具体描述

支付宝每天早上起来都会被系统杀死（一加7Pro 氢OS Android12）所有能给的权限都给了 使用以前的芝麻粒没有出现支付宝被系统杀死的情况，能不能增加保活机制

**Comment by s36376149** [comment]
保活已经支持，不保活查看自己手机是否限制了后台，支付宝是否未加锁，是否启动了限制了锁屏清理后台

**Comment by success-crypto** [comment]
> 保活已经支持，不保活查看自己手机是否限制了后台，支付宝是否未加锁，是否启动了限制了锁屏清理后台

我查看了一下手机设置，估计是应为电池选项里面开启了睡眠待机优化导致的
