### ISSUE TITLE
能否导出配置文件或者云端同步？

### ISSUE THREAD

**Issue by gmikeup** [TKaxv-7S/Sesame-TK#70]
### 增强类型

功能型增强

### 具体描述

之前的版本，基本都会有本地的配置文件，json或者其他的文本格式，软件出现bug之类的， 可以直接清理数据，自动读取配置文件，部分软件还有同步坚果云的功能，方便多机同步

**Comment by ritaferni** [comment]
+1

**Comment by Zhangfanyu1222** [comment]
配置文件目录在这捏
/storage/emulated/0/Android/media/com.eg.android.AlipayGphone/sesame/config_v2.json

**Comment by gmikeup** [comment]
感谢感谢，找到了
