### ISSUE TITLE
请求优化兑换限时双击卡，兑换前先检测背包里双击卡数量

### ISSUE THREAD

**Issue by alinnse** [TKaxv-7S/Sesame-TK#71]
### 增强类型

优化型增强

### 具体描述

请求优化： 兑换限时双击卡先判断背包限时双击卡数量，背包里限时双击卡大于要兑换数量则取消兑换，少了几个则兑换几个。

任务里经常可以领限时双击卡，导致有些限时双击卡过期失效了，故希望优化，谢谢。

**Comment by xzcgg** [comment]
多号怎么处理呢，切小号不需要换

**Comment by alinnse** [comment]
目前没有大小号、号码切换的计划

还不支持大小号跟切号呢。有大小号先搞搞双开单独配置小号？
