### ISSUE TITLE
更新1.2.6.1之后，切换账号提示，模块被禁用

### ISSUE THREAD

**Issue by magisk317** [TKaxv-7S/Sesame-TK#81]
### 程序版本 / 框架版本 / 模块版本

10.6.0.8500，lsp 1.9.3，1.2.6.1

### 系统版本 / Android版本

hyperos，eu，Android14

### 详细描述问题发生的具体原因

主账号正常，切换第一个小号正常，切换第二个小号的时候提示芝麻粒已禁用

主账号收取正常，第一个小号不收取自己能量，但是其他操作正常，如送能量，送道具，以及其他任务等，第二个小号提示模块被禁用，无任何动作

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>
11:45:25.703: 集市逛街👀[获得:能量15g]
11:45:26.987: 服务正在恢复中，请稍后再来！
11:45:27.083: 服务正在恢复中，请稍后再来！
11:45:27.142: 集市逛街👀[获得:能量15g]
11:45:27.142: 执行结束-蚂蚁森林
11:45:28.116: 服务正在恢复中，请稍后再来！
11:45:28.153: 服务正在恢复中，请稍后再来！
11:45:29.250: 服务正在恢复中，请稍后再来！
11:45:29.254: 服务正在恢复中，请稍后再来！
11:45:30.267: 服务正在恢复中，请稍后再来！
11:45:30.398: 服务正在恢复中，请稍后再来！
11:45:31.998: 完成任务🕴🏻[逛一逛优品会场]
11:45:32.736: 完成任务🕴🏻[逛一逛优品会场]
11:47:27.458: 开始加载
11:47:27.466: 芝麻粒已禁用
11:47:27.466: 用户已切换
11:48:26.161: 开始加载
11:48:26.192: 芝麻粒已禁用
11:48:41.825: 开始加载
11:48:41.855: 芝麻粒已禁用
</code></pre></details>

**Comment by magisk317** [comment]
首页导出异常log
[error.2024-06-29.log](https://github.com/user-attachments/files/16038648/error.2024-06-29.log)

**Comment by yi-boide** [comment]
切换账号后需要重新配置相关设置

**Comment by magisk317** [comment]
> 切换账号后需要重新配置相关设置

多谢，刚发现，切换之后模块里的启用状态是关闭
