### ISSUE TITLE
1.2.6.1兑换无限制双击卡在切换账号之后计算错误

### ISSUE THREAD

**Issue by lingluan001** [TKaxv-7S/Sesame-TK#84]
### 程序版本 / 框架版本 / 模块版本

10.6.10.8000/1.9.6/1.2.6.1

### 系统版本 / Android版本

ColorOS

### 详细描述问题发生的具体原因

兑换无限制双击卡的计数方式不正确。假设设置的兑换次数是5，那么第一次可以正常兑换5次，如果此时切换账号，新账号不会再兑换，估计是系统判断已经兑换完5次了。但是如果此时将兑换次数改为6，那么芝麻粒就会再兑换一次，此时查看新切换的账号里只成功兑换了1个。这说明这个兑换的计数方式有问题。

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by Liujishou** [comment]
本来是按照单账号写，后续再优化吧
