### ISSUE TITLE
近几个版本，蚂蚁庄园无法领取饲料。

### ISSUE THREAD

**Issue by tycoontin** [TKaxv-7S/Sesame-TK#87]
### 程序版本 / 框架版本 / 模块版本

1.2.6.2

### 系统版本 / Android版本

Android 13  MIUI14

### 详细描述问题发生的具体原因

如题，并提示“人气大爆发，请稍后再试”

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by ritaferni** [comment]
这个问题和弹窗代理提示是一体的：弹了肯定领不了，领不了必然弹代理提示~
盼尽快解决

**Comment by yi-boide** [comment]
我这用着正常

**Comment by magisk317** [comment]
环境问题，跟工具无关，你试试手动领取，应该也会报错

**Comment by ritaferni** [comment]
我今天尝试解决了：先关模块，再进支付宝手动领就正常了，再启动模块就ok了。

**Comment by tycoontin** [comment]
> 我今天尝试解决了：先关模块，再进支付宝手动领就正常了，再启动模块就ok了。

关闭模板需要重启么？不重启，还是无效。

**Comment by xxhhabc** [comment]
卸载支付宝重新安装最新版就好了

**Comment by wenwen520168** [comment]
> 卸载支付宝重新安装最新版就好了

有没有最新的支付宝，发一个
