### ISSUE TITLE
模块内部开关异常关闭

### ISSUE THREAD

**Issue by MJRweb** [TKaxv-7S/Sesame-TK#93]
### 程序版本 / 框架版本 / 模块版本

程序版本10.6.8.8000     框架版本 lsp1.9.2     模块版本v1.2.6.2-TK   

### 系统版本 / Android版本

澎湃OS / Android14

### 详细描述问题发生的具体原因

![Screenshot_2024-06-30-18-48-01-033_tkaxv7s xposed sesame](https://github.com/TKaxv-7S/Sesame-TK/assets/74905147/55072a84-11c9-476c-8540-d2b69a8dbd2e)
如图，模块内部开关每次进入模块都显示关闭，其他开关也是关闭状态

### 提供模块问题 Log 或必要 Log

<details><summary>展开查看</summary><pre><code>

(此处粘贴问题 Log)

</code></pre></details>

**Comment by yi-boide** [comment]
强制关闭支付宝，然后重启支付宝试试看

**Comment by MJRweb** [comment]
> 强制关闭支付宝，然后重启支付宝试试

试过了不行，基本确认版本问题，回退版本：v1.2.6-test6-TK没得问题，目前挺稳定

**Comment by yi-boide** [comment]
> > 强制关闭支付宝，然后重启支付宝试试
> 
> 试过了不行，基本确认版本问题，回退版本：v1.2.6-test6-TK没得问题，目前挺稳定

可以更新到1.2.6.4试下

**Comment by MJRweb** [comment]
> > > 强制关闭支付宝，然后重启支付宝试试
> > 
> > 
> > 试过了不行，基本确认版本问题，回退版本：v1.2.6-test6-TK没得问题，目前挺稳定
> 
> 可以更新到1.2.6.4试用

啊？github最新不就是1.2.6.2嘛，

**Comment by MJRweb** [comment]
已修复
